### ISSUE TITLE
Compatibility with schemamama 0.1.0+

### ISSUE THREAD

**Issue by daveyarwood** [cmsd2/schemamama_rusqlite#2]
I'd like to use schemamama_rusqlite with schemamama 0.2.0, but it appears I am unable to upgrade the schemamama version to even 0.1.0 without encountering this compilation error:

```
src/db/migrations.rs:14:6: 14:21 error: the trait bound `db::migrations::CreateFoo: schemamama::Migration` is not satisfied [E0277]
src/db/migrations.rs:14 impl SqliteMigration for CreateFoo {
                             ^~~~~~~~~~~~~~~
src/db/migrations.rs:14:6: 14:21 help: run `rustc --explain E0277` to see a detailed explanation
src/db/migrations.rs:14:6: 14:21 note: required by `schemamama_rusqlite::SqliteMigration`
```

Here's the relevant part of my code:

```
use rusqlite;
use schemamama;
use schemamama::Migrator;
use schemamama_rusqlite::{SqliteAdapter, SqliteMigration, SqliteMigrationError};

struct CreateFoo;
migration!(CreateFoo, 1, "create foo table");

// impl schemamama::Migration for CreateFoo {
//     fn version(&self) -> schemamama::Version { 1 }
//     fn description(&self) -> &'static str { "create foo table" }
// }

impl SqliteMigration for CreateFoo {
    fn up(&self, conn: &rusqlite::Connection) -> rusqlite::Result<()> {
        conn.execute("CREATE TABLE users (id BIGINT PRIMARY KEY);", &[]).map(|_| ())
    }

    fn down(&self, conn: &rusqlite::Connection) -> rusqlite::Result<()> {
        conn.execute("DROP TABLE users;", &[]).map(|_| ())
    }
}
```

I also tried commenting out the `migration!` line and uncommenting the code above where I wrote out the `impl` part myself (this ought to be equivalent to what the `migration!` macro expands to) -- same result each time.

The result is also the same if I use schemamama 0.1.0 vs 0.2.0.

If I use schemamama 0.0.11, it compiles successfully.

I spent quite a while looking at the code in this repo and the schemamama repo, and I wasn't able to figure out where the problem is. The weird thing is that [the Migration trait](https://github.com/SkylerLipthay/schemamama/blame/master/src/lib.rs) (lines 11-18) does not appear to have changed at all since schemamama version 0.0.11, but the _really_ weird thing is that as far as I can tell, schemamama hasn't changed whatsoever [between 0.0.11 and 0.1.0](https://github.com/SkylerLipthay/schemamama/commits/master)!

So my best guess is that this may be somehow related to schemamama_rusqlite's schemamama dependency being fixed to 0.0.11... I'm fairly new to Rust, so I'm not really sure how the dependency system works.

**Comment by cmsd2** [comment]
I've pushed new versions for use with 0.1.0 and 0.2.0
It should fix your issue.

My best guess is that due to the old version dependency cargo was giving you multiple versions of schemamama, so you get two incompatible traits called Migration

**Comment by daveyarwood** [comment]
Looks great, and I am now successfully able to use 0.2.0. Thanks a lot for the quick fix! 👍
